brasileirao= ('São Paulo','Coritiba','Corinthians','Atlético-MG','Ceará', 'Avaí','Cuiabá','Juventude','Bragantino','Flamengo', 'Atlético-GO','Santos','Fluminense','Palmeiras', 'Fortaleza', 'América-MG', 'Botafogo', 'Internacional', 'Goiás', 'Athletico-PR')
print('Tabela Brasileirão 2022')
print('=-'*20)
print(f'Os 05 Primeiros: {brasileirao[:5]}')
print('=-'*20)
print(f'Os 04 últimos:{brasileirao[16:]}')
print('=-'*20)
print(f'Ordem alfabetica: {sorted(brasileirao)}')
print('=-'*20)
print(f'O Fortaleza está na {brasileirao.index("Fortaleza")+1}a posição')
print('=-'*20)